export default [{
  path: '/:lang',
  component: require('./app'),
  indexRoute: {
    component: require('./home'),
  },
  childRoutes: [{
    path: 'v6-trial',
    component: require('./v6-trial'),
  }, {
    path: 'v7-trial',
    component: require('./v7-trial'),
  }, {
    path: 'about',
    component: require('./about'),
  }, {
    path: 'events',
    component: require('./events'),
  }, {
    path: 'applications',
    component: require('./applications'),
  }, {
    path: 'applications/additive-manufacturing',
    component: require('./applications/additive-manufacturing'),
  }, {
    path: 'applications/cutting',
    component: require('./applications/cutting'),
  }, {
    path: 'applications/cooperative-robotics',
    component: require('./applications/coop'),
  }, {
    path: 'applications/trimming',
    component: require('./applications/trimming'),
  }, {
    path: 'applications/machining',
    component: require('./applications/machining'),
  }, {
    path: 'applications/deburring',
    component: require('./applications/deburring'),
  }, {
    path: 'applications/welding',
    component: require('./applications/welding'),
  }, {
    path: 'applications/polishing',
    component: require('./applications/polishing'),
  }, {
    path: 'applications/dispensing',
    component: require('./applications/dispensing'),
  }, {
    path: 'applications/deflashing',
    component: require('./applications/deflashing'),
  }, {
    path: 'applications/surface-treatment',
    component: require('./applications/surface'),
  }, {
    path: 'applications/paint',
    component: require('./applications/paint'),
  }, {
    path: 'applications/rail-rotary',
    component: require('./applications/rail-rotary'),
  }, {
    path: 'applications/part-to-tool',
    component: require('./applications/part-to-tool'),
  }, {
    path: 'automatica-2018',
    component: require('./automatica2018'),
  }, {
    path: 'newsroom',
    component: require('./blog'),
  }, {
    path: 'newsroom/:post',
    component: require('./blog-post'),
  }, {
    path: 'contact',
    component: require('./contact'),
  }, {
    path: 'contact/information-request',
    component: require('./information-request'),
  }, {
    path: 'contact/information-request-success',
    component: require('./information-request-success')(
        'inforeq-success-message'),
  }, {
    path: 'contact/information-request-success-additive-manufacturing',
    component: require('./information-request-success')(
        'inforeq-success-additive-manufacturing-message'),
  }, {
    path: 'contact/information-request-success-additive-manufacturing-2',
    component: require('./information-request-success')(
        'inforeq-success-additive-manufacturing-message-2'),
  }, {
    path: 'contact/information-request-success-additive-manufacturing-3',
    component: require('./information-request-success')(
        'inforeq-success-additive-manufacturing-message-3'),
  }, {
    path: 'contact/information-request-success-additive-manufacturing-4',
    component: require('./information-request-success')(
        'inforeq-success-additive-manufacturing-message-4'),
  }, {
    path: 'contact/information-request-success-generic-1',
    component: require('./information-request-success')(
        'inforeq-success-generic-message-1'),
  }, {
    path: 'contact/information-request-success-generic-2',
    component: require('./information-request-success')(
        'inforeq-success-generic-message-2'),
  }, {
    path: 'contact/information-request-success-generic-3',
    component: require('./information-request-success')(
        'inforeq-success-generic-message-3'),
  }, {
    path: 'contact/information-request-success-generic-4',
    component: require('./information-request-success')(
        'inforeq-success-generic-message-4'),
  }, {
    path: 'contact/information-request-success-generic-5',
    component: require('./information-request-success')(
        'inforeq-success-generic-message-5'),
  }, {
    path: 'contact/information-request-success-generic-6',
    component: require('./information-request-success')(
        'inforeq-success-generic-message-6'),
  }, {
    path: 'contact/contact-me-request',
    component: require('./contact-me-request'),
  }, {
    path: 'contact/live-demo-request',
    component: require('./live-demo-request'),
  }, {
    path: 'disclaimer',
    component: require('./disclaimer'),
  }, {
    path: 'eula',
    component: require('./eula'),
  }, {
    path: 'Eula',
    component: require('./eula'),
  }, {
    path: 'EULA',
    component: require('./eula'),
  }, {
    path: 'gdpr',
    component: require('./gdpr'),
  }, {
    path: 'partners',
    component: require('./partners'),
  }, {
    path: 'privacy',
    component: require('./privacy'),
  }, {
    path: 'products',
    component: require('./products'),
  }, {
    path: 'whats-new',
    component: require('./whats-new-v66'),
  }, {
    path: 'success-stories',
    component: require('./success-stories'),
  }, {
    path: 'success-stories/:post',
    component: require('./success-stories-post'),
  }, {
    path: 'why-robotmaster',
    component: require('./why-robotmaster'),
  }, {
    path: '404',
    component: require('./not-found-page'),
  }, {
    path: '*',
    component: require('./not-found-page'),
  }],
}];